apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: picker-vision

resources:
  - configmap.yaml
  - redis.yaml
  - order-service.yaml
  - event-processor.yaml
  - websocket-hub.yaml
  - api-gateway.yaml
  - web-ui.yaml

images:
  - name: ghcr.io/rgconner/picker-vision/api-gateway
    newTag: main
  - name: ghcr.io/rgconner/picker-vision/order-service
    newTag: main
  - name: ghcr.io/rgconner/picker-vision/event-processor
    newTag: main
  - name: ghcr.io/rgconner/picker-vision/websocket-hub
    newTag: main
  - name: ghcr.io/rgconner/picker-vision/web-ui
    newTag: main

labels:
  - pairs:
      app.kubernetes.io/part-of: picker-vision
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
