#!/bin/bash
# =============================================================================
# Picker Vision Node — systemd installer
# =============================================================================
# Installs the picker-vision Docker container as a systemd service so it
# starts automatically on boot and restarts on failure.
#
# Run as the picker user (sudo access required for systemd and docker):
#   bash install-service.sh
#
# To uninstall:
#   bash install-service.sh --uninstall
# =============================================================================
set -e

# ── Defaults (edit here or answer the prompts) ────────────────────────────────
DEFAULT_SERVER_URL="http://192.168.1.100:8000"
DEFAULT_PICKER_ID="picker-1"
DEFAULT_IMAGE="ghcr.io/rgconner/picker-vision/pi-node:main"
DEFAULT_ENV_FILE="$HOME/picker.env"
DEFAULT_SERVICE_NAME="picker-vision"

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; }
header()  { echo -e "\n${BOLD}$*${RESET}"; }

# ── Uninstall path ────────────────────────────────────────────────────────────
if [ "${1}" = "--uninstall" ]; then
    header "Uninstalling Picker Vision service..."
    sudo systemctl stop   "${DEFAULT_SERVICE_NAME}" 2>/dev/null || true
    sudo systemctl disable "${DEFAULT_SERVICE_NAME}" 2>/dev/null || true
    sudo rm -f "/etc/systemd/system/${DEFAULT_SERVICE_NAME}.service"
    sudo systemctl daemon-reload
    success "Service removed. Env file and Docker image left in place."
    info "To also remove the env file:  rm -f ${DEFAULT_ENV_FILE}"
    info "To also remove the image:     docker rmi ${DEFAULT_IMAGE}"
    exit 0
fi

# ── Banner ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║   Picker Vision Node — systemd installer     ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${RESET}"
echo ""

# ── Pre-flight checks ─────────────────────────────────────────────────────────
header "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
    error "Docker is not installed."
    error "Install it with:  curl -fsSL https://get.docker.com | sh"
    exit 1
fi
success "Docker found: $(docker --version)"

if ! groups | grep -q docker && [ "$(id -u)" != "0" ]; then
    warn "Current user is not in the 'docker' group."
    warn "You may be prompted for a password when docker pull runs."
    warn "To fix permanently:  sudo usermod -aG docker $USER  (then log out and back in)"
fi

if ! command -v systemctl &>/dev/null; then
    error "systemd is not available on this system."
    exit 1
fi
success "systemd found."

# Check for video devices
VIDEO_DEVICES=$(ls /dev/video* 2>/dev/null || true)
if [ -z "$VIDEO_DEVICES" ]; then
    warn "No /dev/video* devices found right now."
    warn "Make sure the USB camera is connected before starting the service."
else
    success "Video devices found: $(echo $VIDEO_DEVICES | tr '\n' ' ')"
fi

# ── Interactive configuration ─────────────────────────────────────────────────
header "Configuration"
echo "Press Enter to accept the default shown in [brackets]."
echo ""

read -rp "  Server URL  (x86 server IP:port) [${DEFAULT_SERVER_URL}]: " INPUT_SERVER_URL
SERVER_URL="${INPUT_SERVER_URL:-$DEFAULT_SERVER_URL}"

read -rp "  Picker ID   (unique per station)  [${DEFAULT_PICKER_ID}]: " INPUT_PICKER_ID
PICKER_ID="${INPUT_PICKER_ID:-$DEFAULT_PICKER_ID}"

read -rp "  Docker image                      [${DEFAULT_IMAGE}]: " INPUT_IMAGE
IMAGE="${INPUT_IMAGE:-$DEFAULT_IMAGE}"

read -rp "  Env file path                     [${DEFAULT_ENV_FILE}]: " INPUT_ENV_FILE
ENV_FILE="${INPUT_ENV_FILE:-$DEFAULT_ENV_FILE}"

read -rp "  Service name                      [${DEFAULT_SERVICE_NAME}]: " INPUT_SERVICE_NAME
SERVICE_NAME="${INPUT_SERVICE_NAME:-$DEFAULT_SERVICE_NAME}"

# ── Write env file ────────────────────────────────────────────────────────────
header "Writing env file to ${ENV_FILE}..."

# If env file already exists, back it up
if [ -f "$ENV_FILE" ]; then
    BACKUP="${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
    cp "$ENV_FILE" "$BACKUP"
    warn "Existing env file backed up to ${BACKUP}"
fi

cat > "$ENV_FILE" <<EOF
# Picker Vision Node — generated by install-service.sh on $(date)
# Edit this file and then run:  sudo systemctl restart ${SERVICE_NAME}

SERVER_URL=${SERVER_URL}
PICKER_ID=${PICKER_ID}

# Camera: leave blank for auto-detection, or set to 0, 1, 2...
CAMERA_INDEX=

FRAME_WIDTH=640
FRAME_HEIGHT=480
FRAME_FPS=15
MJPEG_QUALITY=80
CONTROL_PORT=8081
STAGING_AREA_THRESHOLD=50,150
MIN_STAGING_AREA=5000
OFFLINE_BUFFER_PATH=/tmp/picker-events-offline.jsonl
EOF

chmod 600 "$ENV_FILE"   # readable only by this user — keeps SERVER_URL private
success "Env file written: ${ENV_FILE}"

# ── Pull the Docker image ─────────────────────────────────────────────────────
header "Pulling Docker image ${IMAGE}..."
docker pull "$IMAGE"
success "Image ready."

# ── Write systemd unit file ───────────────────────────────────────────────────
header "Writing systemd service /etc/systemd/system/${SERVICE_NAME}.service..."

UNIT_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

sudo tee "$UNIT_FILE" > /dev/null <<EOF
[Unit]
Description=Picker Vision Node (${PICKER_ID})
Documentation=https://github.com/Rgconner/picker-vision
# Start after Docker and the network are ready
After=docker.service network-online.target
Requires=docker.service
Wants=network-online.target

[Service]
User=${USER}
Restart=on-failure
RestartSec=10
# How long to wait for the container to stop cleanly before killing it
TimeoutStopSec=30

# Remove any stale container with this name before starting
ExecStartPre=-/usr/bin/docker rm -f ${SERVICE_NAME}

# Pull latest image before each start (remove this line to skip pull on boot)
ExecStartPre=/usr/bin/docker pull ${IMAGE}

# Start the container
# --rm            : remove container when it stops (systemd handles restart)
# --name          : named container so ExecStop can find it
# --env-file      : reads all configuration from ${ENV_FILE}
# --device-cgroup-rule + -v /dev:/dev : exposes ALL USB video devices so
#                   camera auto-detection can find the right one regardless
#                   of which /dev/videoN the camera lands on at boot
# -p 8080:8080    : MJPEG stream (accessed by the server to proxy to browser)
# -p 8081:8081    : local control API (Start/Stop/Validate from the server)
ExecStart=/usr/bin/docker run \
    --rm \
    --name ${SERVICE_NAME} \
    --env-file ${ENV_FILE} \
    --device-cgroup-rule='c 81:* rmw' \
    -v /dev:/dev \
    -p 8080:8080 \
    -p 8081:8081 \
    ${IMAGE}

ExecStop=/usr/bin/docker stop ${SERVICE_NAME}

# Write logs to the journal (view with: journalctl -u ${SERVICE_NAME} -f)
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}

[Install]
WantedBy=multi-user.target
EOF

success "Unit file written: ${UNIT_FILE}"

# ── Enable and start the service ──────────────────────────────────────────────
header "Enabling and starting the service..."

sudo systemctl daemon-reload
sudo systemctl enable "${SERVICE_NAME}"
sudo systemctl start  "${SERVICE_NAME}"

# Give it a moment to initialise
sleep 3

# ── Status report ─────────────────────────────────────────────────────────────
header "Service status"
sudo systemctl status "${SERVICE_NAME}" --no-pager || true

echo ""
echo -e "${BOLD}══════════════════════════════════════════════${RESET}"
success "Picker Vision is installed and running as a system service."
echo ""
echo "  Useful commands:"
echo ""
echo -e "  ${CYAN}sudo systemctl status  ${SERVICE_NAME}${RESET}   — current status"
echo -e "  ${CYAN}sudo systemctl restart ${SERVICE_NAME}${RESET}   — restart after config change"
echo -e "  ${CYAN}sudo systemctl stop    ${SERVICE_NAME}${RESET}   — stop"
echo -e "  ${CYAN}journalctl -u ${SERVICE_NAME} -f${RESET}         — live logs"
echo -e "  ${CYAN}docker logs -f ${SERVICE_NAME}${RESET}           — container logs (while running)"
echo ""
echo "  To change settings, edit:  ${ENV_FILE}"
echo "  Then run:  sudo systemctl restart ${SERVICE_NAME}"
echo ""
echo "  To uninstall:"
echo "    bash $0 --uninstall"
echo ""
